server:
  port: 8080
spring:
  application:
    name: todo-project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${$IP_DATABASE:localhost}:${DATABASE_PORT:3307}/${DATABASE_NAME:tododb}?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jwt:
    secret: ${SECRET}
    expiration: 900000
springdoc:
  swagger-ui:
    path: /docs